apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: papas-pizzeria-service
spec:
  template:
    spec:
      containers:
        - image: gcr.io/YOUR_PROJECT_ID/papas-pizzeria:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres.gbtqiyalzzacoxjmzrxj"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "YoureMyLittleFreakNow"
