# cloudbuild.yaml
steps:
  # Step 1: Build the Spring Boot JAR
  - name: 'maven:3.8.5-openjdk-17'
    entrypoint: 'mvn'
    args: ['clean', 'package', '-DskipTests']

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/papaspizzeria-repo/papaspizzeria:$COMMIT_SHA'
      - '.'

  # Step 3: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/papaspizzeria-repo/papaspizzeria:$COMMIT_SHA'

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy pizza-pos-service \
          --image us-central1-docker.pkg.dev/$PROJECT_ID/papaspizzeria-repo/papaspizzeria:$COMMIT_SHA \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars SPRING_DATASOURCE_URL=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres,SPRING_DATASOURCE_USERNAME=postgres.gbtqiyalzzacoxjmzrxj,SPRING_DATASOURCE_PASSWORD=YoureMyLittleFreakNow,SPRING_JPA_HIBERNATE_DDL_AUTO=update

# Declare the images Cloud Build will produce
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/papaspizzeria-repo/papaspizzeria:$COMMIT_SHA'
